name: Keep my Duolingo streak

on:
  schedule:
  # Runs 3AM UTC, 10PM ET
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 1
