name: Keep my Duolingo streak

on:
  schedule:
  # Runs 7AM ET
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: 1

      - run: |
          echo $(date) > lastrun
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add lastrun
          git commit -m "update lastrun"
          git push
